# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#platform :ios, '9.0'
use_frameworks!
target 'swiftLearning' do
    #-- OC库
    pod 'MBProgressHUD'
    
    #-- swift5.0
    pod 'Moya'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'Alamofire'


end
